Update hello-indigo.md
PurpleKingdomGames/indigo-website pull request #17
Opened 2021-08-27 15:32 UTC by paulaylingdev

Fix a couple of example references which don't work to match [hello-indigo-sbt](https://github.com/PurpleKingdomGames/hello-indigo-sbt/blob/master/src/main/scala/HelloIndigo.scala#L69-L96)

2021-08-27 16:16 UTC, davesmith00000 requested changes
Thank you very much for updating this! Just one of the changes is incorrect, see my comment, if you could undo it I'll be delighted to merge it.

2021-08-27 16:16 UTC, davesmith00000 commented on indigodocs/quickstart/hello-indigo.md
> +When a mouse click is noticed, we call our `addDot` method with a new Dot, providing the orbital distance and the angle from the center of the screen to the point where we clicked the mouse using `Ma
This is an excellent observation, however, `atan2`'s arguments are `y` then `x` (you can check in Javas docs), so this is not a typo I'm afraid.
Why then is the position used in the x,y order in the code you might ask? Try swapping them! It's necessary to have the dot appear under the mouse cursor.
In any case, this change will need to be put back.

2021-08-27 20:23 UTC, davesmith00000 commented on indigodocs/quickstart/hello-indigo.md
> +When a mouse click is noticed, we call our `addDot` method with a new Dot, providing the orbital distance and the angle from the center of the screen to the point where we clicked the mouse using `Ma
> This is an excellent observation

I wasn't being sarcastic by the way, I clearly use the arguments the other way around later. Perfectly reasonable to assume it's a typo. :-)

2021-08-28 12:00 UTC, paulaylingdev commented on indigodocs/quickstart/hello-indigo.md
> +When a mouse click is noticed, we call our `addDot` method with a new Dot, providing the orbital distance and the angle from the center of the screen to the point where we clicked the mouse using `Ma
Makes sense! Thanks for the explanation

2021-08-28 12:45 UTC, davesmith00000 approved these changes

2021-08-28 12:45 UTC, merged